name: Deep Recon

on:
  workflow_dispatch:

env:
  TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update || echo "apt update failed"
          sudo apt install -y python3-pip git wget python3-venv || echo "apt install failed"
          pip3 install pipx || echo "pipx install failed"
          pipx ensurepath || echo "pipx ensurepath failed"

          pipx install bbot || echo "bbot install failed"
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest || echo "httpx install failed"
          go install github.com/projectdiscovery/katana/cmd/katana@latest || echo "katana install failed"
          go install github.com/LukaSikic/subzy@latest || echo "subzy install failed"
          go install github.com/tomnomnom/waybackurls@latest || echo "waybackurls install failed"
          go install github.com/lc/gau/v2/cmd/gau@latest || echo "gau install failed"

          echo "$HOME/go/bin" >> $GITHUB_PATH

          git clone https://github.com/FortyNorthSecurity/EyeWitness.git || echo "EyeWitness clone failed"
          cd EyeWitness
          chmod +x setup.sh || echo "chmod failed"
          sudo ./setup.sh || echo "EyeWitness setup failed"
          cd ..

          git clone https://github.com/devanshbatham/ParamSpider.git || echo "ParamSpider clone failed"
          cd ParamSpider
          pip install -r requirements.txt || echo "ParamSpider requirements install failed"
          cd ..

      - name: Subdomain Enumeration (BBOT)
        continue-on-error: true
        run: |
          mkdir bbot_output
          bbot -t $TARGET_DOMAIN -o bbot_output || echo "BBOT failed"
          cp bbot_output/*/output.txt subdomains.txt || echo "Copying BBOT output failed"

      - name: Check Alive Subdomains (HTTPX)
        continue-on-error: true
        run: |
          cat subdomains.txt | httpx -silent -o alive_subdomains.txt || echo "HTTPX failed"

      - name: Crawl Alive Subdomains (Katana)
        continue-on-error: true
        run: |
          katana -list alive_subdomains.txt -o endpoints.txt || echo "Katana failed"

      - name: Screenshot Alive Subdomains (EyeWitness)
        continue-on-error: true
        run: |
          mkdir -p screenshots
          cd EyeWitness
          python3 EyeWitness.py --web -f ../alive_subdomains.txt --threads 5 -d ../screenshots/ || echo "EyeWitness failed"
          cd ..

      - name: Subdomain Takeover Scan (Subzy)
        continue-on-error: true
        run: |
          subzy run --targets alive_subdomains.txt > subzy_results.txt || echo "Subzy failed"

      - name: Parameter Discovery (ParamSpider)
        continue-on-error: true
        run: |
          cd ParamSpider
          python3 paramspider.py -d $TARGET_DOMAIN > ../paramspider_results.txt || echo "ParamSpider failed"
          cd ..

      - name: Gather URLs (WaybackURLs + GAU)
        continue-on-error: true
        run: |
          cat alive_subdomains.txt | waybackurls > waybackurls.txt || echo "WaybackURLs failed"
          cat alive_subdomains.txt | gau > gau.txt || echo "GAU failed"
          sort -u waybackurls.txt gau.txt > urls.txt || echo "Sorting failed"

      - name: Upload Recon Results
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: |
            subdomains.txt
            alive_subdomains.txt
            endpoints.txt
            screenshots/
            subzy_results.txt
            paramspider_results.txt
            urls.txt
