name: Recon Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain to scan'
        required: true

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      DOMAIN: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Python / ParamSpider ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ParamSpider
        run: |
          git clone https://github.com/devanshbatham/ParamSpider paramspider
          cd paramspider
          pip install .

      - name: Run ParamSpider
        run: |
          cd paramspider
          paramspider -d $DOMAIN

      # --- Nuclei (Prebuilt Binary) ---
      - name: Download Nuclei prebuilt binary
        run: |
          mkdir -p ~/tools
          curl -L https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.4.2_linux_amd64.zip -o nuclei.zip
          unzip nuclei.zip -d ~/tools
          chmod +x ~/tools/nuclei

      - name: Update Nuclei templates
        run: |
          ~/tools/nuclei -update-templates

      - name: Run Nuclei scan
        run: |
          ~/tools/nuclei -l paramspider/results/${{ env.DOMAIN }}.txt \
                         -o nuclei_results.txt \
                         -stats -stats-interval 10s \
                         -ni

      # --- Artifacts ---
      - name: Upload ParamSpider output
        uses: actions/upload-artifact@v4
        with:
          name: paramspider-output
          path: paramspider/results/${{ env.DOMAIN }}.txt

      - name: Upload Nuclei scan results
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results
          path: nuclei_results.txt
