name: Deep Recon

on:
  workflow_dispatch:

env:
  TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update || echo "apt update failed"
          sudo apt install -y python3-pip git wget python3-venv xvfb firefox-geckodriver \
            || echo "apt install failed"

      - name: Install BBOT & Python Recon Tools
        run: |
          pip3 install pipx || echo "pipx install failed"
          pipx install bbot || echo "bbot install failed"
          git clone https://github.com/devanshbatham/ParamSpider.git || echo "ParamSpider clone failed"
          cd ParamSpider
          pip3 install . || echo "ParamSpider install failed"   # correct installer :contentReference[oaicite:5]{index=5}
          cd ..

      - name: Install Go-based Recon Tools
        run: |
          # HTTPX & Katana from ProjectDiscovery
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest  || echo "httpx install failed"
          go install github.com/projectdiscovery/katana/cmd/katana@latest || echo "katana install failed"
          # Subzy from PentestPad :contentReference[oaicite:6]{index=6}
          go install github.com/PentestPad/subzy@latest                  || echo "subzy install failed"
          # WaybackURLs & GAU
          go install github.com/tomnomnom/waybackurls@latest            || echo "waybackurls install failed"
          go install github.com/lc/gau/v2/cmd/gau@latest                || echo "gau install failed"
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install EyeWitness
        run: |
          git clone https://github.com/FortyNorthSecurity/EyeWitness.git || echo "EyeWitness clone failed"
          cd EyeWitness/Python/setup
          chmod +x setup.sh                            || echo "chmod failed"
          sudo ./setup.sh                              || echo "EyeWitness install failed"  # correct path :contentReference[oaicite:7]{index=7}
          cd ../../..

      - name: Subdomain Enumeration (BBOT)
        continue-on-error: true
        run: |
          mkdir -p bbot_output
          bbot -t $TARGET_DOMAIN -o bbot_output       || echo "BBOT failed"
          cp bbot_output/*/output.txt subdomains.txt  || echo "Copying BBOT output failed"   # fixes directory vs file :contentReference[oaicite:8]{index=8}

      - name: Check Alive Subdomains (HTTPX)
        continue-on-error: true
        run: |
          cat subdomains.txt | httpx -silent -o alive_subdomains.txt || echo "HTTPX failed"

      - name: Crawl Alive Subdomains (Katana)
        continue-on-error: true
        run: |
          katana -list alive_subdomains.txt -o endpoints.txt || echo "Katana failed"

      - name: Screenshot Alive Subdomains (EyeWitness)
        continue-on-error: true
        run: |
          mkdir -p screenshots
          xvfb-run -a python3 EyeWitness/Python/EyeWitness.py \
            --web -f alive_subdomains.txt --threads 5 -d screenshots/ \
            || echo "EyeWitness screenshot failed"

      - name: Subdomain Takeover Scan (Subzy)
        continue-on-error: true
        run: |
          subzy run --targets alive_subdomains.txt > subzy_results.txt || echo "Subzy failed"

      - name: Parameter Discovery (ParamSpider)
        continue-on-error: true
        run: |
          paramspider -d $TARGET_DOMAIN > paramspider_results.txt || echo "ParamSpider failed"

      - name: Gather URLs (WaybackURLs + GAU)
        continue-on-error: true
        run: |
          cat alive_subdomains.txt | waybackurls > waybackurls.txt || echo "WaybackURLs failed"
          cat alive_subdomains.txt | gau         > gau.txt         || echo "GAU failed"
          sort -u waybackurls.txt gau.txt > urls.txt  || echo "Sorting failed"

      - name: Upload Recon Results
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: |
            subdomains.txt
            alive_subdomains.txt
            endpoints.txt
            screenshots/
            subzy_results.txt
            paramspider_results.txt
            urls.txt
