name: Recon Automation

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Enter the domain to scan'
        required: true
        default: 'example.com'

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go (for gowitness)
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install Dependencies
      run: |
        # Install assetfinder
        wget https://github.com/assetfinder/assetfinder/releases/download/v1.1.1/assetfinder-linux-amd64 -O /usr/local/bin/assetfinder
        chmod +x /usr/local/bin/assetfinder
        
        # Install Subfinder
        wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.6/subfinder-linux-amd64 -O /usr/local/bin/subfinder
        chmod +x /usr/local/bin/subfinder
        
        # Install Amass
        wget https://github.com/OWASP/Amass/releases/download/v3.14.4/amass-linux-amd64-v3.14.4.zip
        unzip amass-linux-amd64-v3.14.4.zip -d amass
        chmod +x amass/amass
        mv amass/amass /usr/local/bin/

        # Install Gowitness
        wget https://github.com/sensepost/gowitness/releases/download/v2.0.0/gowitness-linux-amd64 -O /usr/local/bin/gowitness
        chmod +x /usr/local/bin/gowitness
        
        # Install getJS
        git clone https://github.com/Delevir/getJS.git
        cd getJS
        pip3 install -r requirements.txt
        cd ..

        # Install LinkFinder
        git clone https://github.com/GerbenJavado/LinkFinder.git
        cd LinkFinder
        pip3 install -r requirements.txt
        cd ..

    - name: Run Subdomain Enumeration with Assetfinder
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        assetfinder --subs-only $DOMAIN > assetfinder_subdomains.txt

    - name: Run Subdomain Enumeration with Subfinder
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        subfinder -d $DOMAIN -o subfinder_subdomains.txt

    - name: Run Subdomain Enumeration with Amass
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        amass enum -d $DOMAIN -o amass_subdomains.txt

    - name: Take Screenshots of Targets Using Gowitness
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        gowitness batch --urls subfinder_subdomains.txt --destination screenshots/

    - name: Scrape JS Files with getJS
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        while IFS= read -r subdomain; do
          getjs "$subdomain" --output "js_files/$subdomain"
        done < subfinder_subdomains.txt

    - name: Use LinkFinder on JS Files
      run: |
        DOMAIN="${{ github.event.inputs.domain }}"  # Get the domain input from the workflow dispatch
        for file in js_files/*; do
          python3 LinkFinder/linkfinder.py -i "$file" -o "linkfinder_output/$(basename "$file").txt"
        done

    - name: Search for Endpoints Using Grep
      run: |
        grep -r "admin" * > admin_endpoints.txt
        grep -r "login" * > login_endpoints.txt
        grep -r "dashboard" * > dashboard_endpoints.txt

    - name: Upload Results as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: recon-results
        path: |
          assetfinder_subdomains.txt
          subfinder_subdomains.txt
          amass_subdomains.txt
          screenshots/
          js_files/
          linkfinder_output/
          admin_endpoints.txt
          login_endpoints.txt
          dashboard_endpoints.txt
