name: ParamSpider Run

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to scan'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ParamSpider
        run: git clone https://github.com/devanshbatham/paramspider.git
      - name: Install ParamSpider
        run: |
          cd paramspider
          pip install .
      - name: Run ParamSpider
        run: |
          cd paramspider
          paramspider -d ${{ github.event.inputs.domain }}
      - name: Show Results
        run: |
          cat paramspider/results/${{ github.event.inputs.domain }}.txt
