name: Deep Recon

on:
  workflow_dispatch:

env:
  TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours to stay within the 6-hour limit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git nmap perl wget
          pip3 install pipx
          pipx ensurepath
          pipx install bbot
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          git clone https://github.com/FortyNorthSecurity/EyeWitness.git
          cd EyeWitness/Python && sudo ./setup.sh
          go install github.com/LukaSikic/subzy@latest
          git clone https://github.com/devanshbatham/ParamSpider.git
          cd ParamSpider && pip install -r requirements.txt
          go install github.com/tomnomnom/waybackurls@latest
          go install github.com/lc/gau/v2/cmd/gau@latest

      - name: Subdomain Enumeration with BBOT
        run: |
          bbot -d $TARGET_DOMAIN -o subdomains.txt

      - name: Check Alive Subdomains with HTTPX
        run: |
          cat subdomains.txt | httpx -silent -o alive_subdomains.txt

      - name: Crawl Alive Subdomains with Katana
        run: |
          katana -list alive_subdomains.txt -o endpoints.txt

      - name: Capture Screenshots with EyeWitness
        run: |
          cd EyeWitness/Python
          ./EyeWitness.py --web -f ../../alive_subdomains.txt --threads 5 -d ../../screenshots/

      - name: Detect Subdomain Takeovers with Subzy
        run: |
          subzy run --targets alive_subdomains.txt > subzy_results.txt

      - name: Discover Parameters with ParamSpider
        run: |
          cd ParamSpider
          python3 paramspider.py -d $TARGET_DOMAIN > ../paramspider_results.txt

      - name: Gather URLs with WaybackURLs and GAU
        run: |
          cat alive_subdomains.txt | waybackurls > waybackurls.txt
          cat alive_subdomains.txt | gau > gau.txt
          sort -u waybackurls.txt gau.txt > urls.txt

      - name: Upload Reconnaissance Results
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: |
            subdomains.txt
            alive_subdomains.txt
            endpoints.txt
            screenshots/
            subzy_results.txt
            paramspider_results.txt
            urls.txt
