name: Subdomain ParamSpider Scan

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Root domain (e.g., example)'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Tools
        run: |
          pip install dnspython
          sudo apt-get update
          sudo apt-get install -y amass
      - name: Find Subdomains with Amass
        run: |
          amass enum -d ${{ github.event.inputs.domain }}.com -o subdomains.txt
      - name: Clone ParamSpider
        run: |
          git clone https://github.com/devanshbatham/paramspider
      - name: Install ParamSpider
        run: |
          cd paramspider
          pip install .
      - name: Run ParamSpider on Subdomains
        run: |
          cd paramspider
          mkdir -p results
          while read sub; do
            paramspider -d "$sub"
          done < ../subdomains.txt
      - name: Show All Results
        run: |
          cat paramspider/results/*.txt
