name: Run ReconFTW (cached)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Domain to scan (example: hackerone.com)'
        required: true
        default: 'hackerone.com'

jobs:
  reconftw-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache ReconFTW Tools
        uses: actions/cache@v4
        with:
          path: |
            ~/go
            ~/tools
            ~/.local/bin
          key: ${{ runner.os }}-reconftw-${{ hashFiles('reconftw/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-reconftw-

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y git curl unzip jq

      - name: Clone reconftw
        run: |
          git clone https://github.com/six2dez/reconftw.git
          cd reconftw
          chmod +x install.sh reconftw.sh

      - name: Install ReconFTW Tools (if not cached)
        run: |
          cd reconftw
          ./install.sh

      - name: Run ReconFTW
        run: |
          cd reconftw
          ./reconftw.sh -d ${{ github.event.inputs.target }} -r

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: reconftw-results
          path: reconftw/results/
