name: Run mainRecon

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Enter the program target (example: hackerone)'
        required: true
        default: 'hackerone'

jobs:
  mainrecon-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull and Run mainRecon
        run: |
          docker pull l34r00t/mainrecon

          docker run --rm -it \
            --env chat_ID="${{ secrets.CHAT_ID }}" \
            --env token="${{ secrets.BOT_TOKEN }}" \
            --env findomain_fb_token="${{ secrets.FB_TOKEN }}" \
            --env findomain_spyse_token="${{ secrets.SPYSE_TOKEN }}" \
            --env findomain_virustotal="${{ secrets.VIRUSTOTAL_TOKEN }}" \
            --env findomain_securitytrails_token="${{ secrets.SECURITYTRAILS_TOKEN }}" \
            -v ${{ github.workspace }}/targets:/mainData \
            --name mainrecon \
            l34r00t/mainrecon \
            -p ${{ github.event.inputs.target }} -f targets.txt
