name: Recon Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain to scan'
        required: true

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      DOMAIN: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Python/ParamSpider ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ParamSpider
        run: |
          git clone https://github.com/devanshbatham/ParamSpider paramspider
          cd paramspider
          pip install .

      - name: Run ParamSpider
        run: |
          cd paramspider
          paramspider -d $DOMAIN

      # --- Go/Nuclei ---
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - name: Cache Go build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Install Nuclei from source with caching
        run: |
          mkdir -p ~/tools
          cd ~/tools
          if [ ! -f nuclei ]; then
            git clone https://github.com/projectdiscovery/nuclei.git
            cd nuclei/v3/cmd/nuclei
            go build -o ~/tools/nuclei .
          fi

      - name: Update Nuclei templates
        run: |
          ~/tools/nuclei -update-templates

      - name: Run Nuclei scan
        run: |
          ~/tools/nuclei -l paramspider/results/$DOMAIN.txt \
                         -o nuclei_results.txt \
                         -stats -stats-interval 10s \
                         -ni

      # --- Artifacts ---
      - name: Upload ParamSpider output
        uses: actions/upload-artifact@v4
        with:
          name: paramspider-output
          path: paramspider/results/$DOMAIN.txt

      - name: Upload Nuclei scan results
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results
          path: nuclei_results.txt
